# Generated by Django 4.0.4 on 2022-04-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('tamaño', 'tamaño')], max_length=100),
        ),
    ]
